version: "3.8"

services:
  backend:
    build: ./backend
    container_name: busopt-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: busopt-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
