version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: bus-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    networks:
      - bus-network

  frontend:
    build:
      context: ./frontend
      args:
        # Pass backend URL into React at build time
        REACT_APP_BACKEND_URL: "http://backend:8000"
    container_name: bus-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bus-network

networks:
  bus-network:
    driver: bridge
